version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  mongodb-test:
    image: mongo
    container_name: mongodb-test
    ports:
      - "27019:27019"
    volumes:
      - ./data/test/mongodb:/data/db  
      